# docker-compose.yml
services:
  exchangerate-mock1:
    build:
      context: .
      dockerfile: ExchangeRateOffers.Mock1/Dockerfile
    container_name: exchangerate-mock1
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080